import type React from "react";
import { LIBRARY_ICONS, VENDOR_ICONS } from "./library";
import type { IconProps } from "./primitives";
import {
  AnchorBreath,
  BellRing,
  EyeOpen,
  FeetGround,
  HeartSettle,
  PhoneFeed,
  PressureKnot,
  ScreenPair,
  ThoughtCloud,
  TimelineTicks,
} from "./icons";
import { ZenMonkPray } from "./icons-detail";
import {
  BottleGlass,
  PodiumStep,
  SadPerson,
  ScatterDots,
  VideoWindow,
  WakeEarly,
} from "./icons-ref";
import {
  ClipboardCheck,
  CloseWave,
  ForkPaths,
  HandKey,
  PauseThink,
  HeartCrack,
  HeartHold,
  Iceberg,
  LinkPair,
  OneFrame,
  PhotoGap,
  PhotoLens,
  PhotoPost,
  SpeechFit,
  ThoughtSupposing,
} from "./icons-foto";
import {
  ArmBase,
  ArmInner,
  ArmPress,
  ArmTendons,
  ArmThree,
  CalmTorso,
  TightTorso,
} from "./icons-punto";
import {
  ClimbCost,
  EyeHalf,
  EyeSeeing,
  EyeShut,
  SparedHeart,
  SwallowedWords,
  WakeNoWill,
} from "./icons-nadie";
import {
  LeftBehind,
  OneWord,
  PhoneCall,
  SandLow,
  StartAgain,
  StillTime1,
  StillTime2,
  StillTime3,
  UseItNow,
} from "./icons-todavia";
import {
  ArrowBody,
  BuddhaTells,
  FirstArrow,
  ProblemOver,
  SecondArrow,
  StressBody,
  TwoArrows,
  WorryLoop,
} from "./icons-flecha";
import {
  AtomProof,
  BedUnfinished,
  CrowdRow,
  EatWalk,
  EatingElsewhere,
  FeelWorse,
  BowlNow,
  HalfDay,
  NotElsewhere,
  RightHere,
  SaidNo,
  StudyPaper,
  UndoneList,
  WalkNow,
  WhereIsPeace,
  ZenAsked,
} from "./icons-zen";

/** Every metaphor available to a storyboard. Add one line to extend it. */
export const ICONS = {
  ...LIBRARY_ICONS,
  ...VENDOR_ICONS,
  anchorBreath: AnchorBreath,
  phoneFeed: PhoneFeed,
  thoughtCloud: ThoughtCloud,
  eyeOpen: EyeOpen,
  bellRing: BellRing,
  feetGround: FeetGround,
  timelineTicks: TimelineTicks,
  pressureKnot: PressureKnot,
  heartSettle: HeartSettle,
  screenPair: ScreenPair,
  zenAsked: ZenAsked,
  zenMonk: ZenMonkPray,
  eatWalk: EatWalk,
  crowdRow: CrowdRow,
  eatingElsewhere: EatingElsewhere,
  bedUnfinished: BedUnfinished,
  atomProof: AtomProof,
  halfDay: HalfDay,
  feelWorse: FeelWorse,
  whereIsPeace: WhereIsPeace,
  notElsewhere: NotElsewhere,
  studyPaper: StudyPaper,
  rightHere: RightHere,
  bowlNow: BowlNow,
  walkNow: WalkNow,
  saidNo: SaidNo,
  undoneList: UndoneList,
  buddhaTells: BuddhaTells,
  twoArrows: TwoArrows,
  firstArrow: FirstArrow,
  secondArrow: SecondArrow,
  arrowBody: ArrowBody,
  worryLoop: WorryLoop,
  stressBody: StressBody,
  problemOver: ProblemOver,
  stillTime1: StillTime1,
  stillTime2: StillTime2,
  stillTime3: StillTime3,
  sandLow: SandLow,
  phoneCall: PhoneCall,
  startAgain: StartAgain,
  leftBehind: LeftBehind,
  oneWord: OneWord,
  useItNow: UseItNow,
  eyeShut: EyeShut,
  eyeHalf: EyeHalf,
  eyeSeeing: EyeSeeing,
  wakeNoWill: WakeNoWill,
  swallowedWords: SwallowedWords,
  sparedHeart: SparedHeart,
  climbCost: ClimbCost,
  armBase: ArmBase,
  armThree: ArmThree,
  armInner: ArmInner,
  armTendons: ArmTendons,
  armPress: ArmPress,
  tightTorso: TightTorso,
  calmTorso: CalmTorso,
  sadPerson: SadPerson,
  scatterDots: ScatterDots,
  bottleGlass: BottleGlass,
  wakeEarly: WakeEarly,
  videoWindow: VideoWindow,
  podiumStep: PodiumStep,
  handKey: HandKey,
  photoPost: PhotoPost,
  heartCrack: HeartCrack,
  pauseThink: PauseThink,
  photoLens: PhotoLens,
  thoughtSupposing: ThoughtSupposing,
  oneFrame: OneFrame,
  icebergHeart: Iceberg,
  linkPair: LinkPair,
  speechFit: SpeechFit,
  photoGap: PhotoGap,
  clipboardCheck: ClipboardCheck,
  forkPaths: ForkPaths,
  heartHold: HeartHold,
  closeWave: CloseWave,
} satisfies Record<string, React.FC<IconProps>>;

export type IconName = keyof typeof ICONS;
