import type React from "react";
import type { IconProps } from "./primitives";
import {
  AnchorBreath,
  BellRing,
  EyeOpen,
  FeetGround,
  HeartSettle,
  PhoneFeed,
  PressureKnot,
  ScreenPair,
  ThoughtCloud,
  TimelineTicks,
} from "./icons";
import { ZenMonkPray } from "./icons-detail";
import {
  BottleGlass,
  PodiumStep,
  SadPerson,
  ScatterDots,
  VideoWindow,
  WakeEarly,
} from "./icons-ref";
import {
  ClipboardCheck,
  CloseWave,
  ForkPaths,
  HandKey,
  HandStop,
  HeartCrack,
  HeartHold,
  Iceberg,
  LinkPair,
  OneFrame,
  PhotoGap,
  PhotoLens,
  PhotoPost,
  SpeechFit,
  ThoughtSupposing,
} from "./icons-foto";
import {
  AtomProof,
  BedUnfinished,
  CrowdRow,
  EatWalk,
  EatingElsewhere,
  FeelWorse,
  HalfDay,
  NotElsewhere,
  WhereIsPeace,
  ZenAsked,
} from "./icons-zen";

/** Every metaphor available to a storyboard. Add one line to extend it. */
export const ICONS = {
  anchorBreath: AnchorBreath,
  phoneFeed: PhoneFeed,
  thoughtCloud: ThoughtCloud,
  eyeOpen: EyeOpen,
  bellRing: BellRing,
  feetGround: FeetGround,
  timelineTicks: TimelineTicks,
  pressureKnot: PressureKnot,
  heartSettle: HeartSettle,
  screenPair: ScreenPair,
  zenAsked: ZenAsked,
  zenMonk: ZenMonkPray,
  eatWalk: EatWalk,
  crowdRow: CrowdRow,
  eatingElsewhere: EatingElsewhere,
  bedUnfinished: BedUnfinished,
  atomProof: AtomProof,
  halfDay: HalfDay,
  feelWorse: FeelWorse,
  whereIsPeace: WhereIsPeace,
  notElsewhere: NotElsewhere,
  sadPerson: SadPerson,
  scatterDots: ScatterDots,
  bottleGlass: BottleGlass,
  wakeEarly: WakeEarly,
  videoWindow: VideoWindow,
  podiumStep: PodiumStep,
  handKey: HandKey,
  photoPost: PhotoPost,
  heartCrack: HeartCrack,
  handStop: HandStop,
  photoLens: PhotoLens,
  thoughtSupposing: ThoughtSupposing,
  oneFrame: OneFrame,
  iceberg: Iceberg,
  linkPair: LinkPair,
  speechFit: SpeechFit,
  photoGap: PhotoGap,
  clipboardCheck: ClipboardCheck,
  forkPaths: ForkPaths,
  heartHold: HeartHold,
  closeWave: CloseWave,
} satisfies Record<string, React.FC<IconProps>>;

export type IconName = keyof typeof ICONS;
